[mysqld]
port=3307
basedir="C:\Users\jpere\Desktop\SistemaDeCobro\mysql"
datadir="C:\Users\jpere\Desktop\SistemaDeCobro\mysql\data"

max_connections=100
key_buffer_size=16M
max_allowed_packet=16M
table_open_cache=64
sort_buffer_size=512K
net_buffer_length=8K
read_buffer_size=256K
read_rnd_buffer_size=512K
myisam_sort_buffer_size=8M

character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci

log_error="C:\Users\jpere\Desktop\SistemaDeCobro\mysql\data\mysql_error.log"
sql_mode=NO_ENGINE_SUBSTITUTION
skip-external-locking
console=off

[client]
port=3307
default-character-set=utf8mb4

[mysql]
default-character-set=utf8mb4
